### ISSUE TITLE
Keras as a L1 model?

### ISSUE THREAD

**Issue by herbzhao** [vecxoz/vecstack#12]
Hi, Thanks again.
I am wondering whether keras can be used as a L1 model.
The only annoying thing is keras fit methods have a epoch arg, which is not standard as other sklearn models.. 

I am wondering how would you implement this?

**Comment by vecxoz** [comment]
For this purpose you can use Scikit-learn wrappers for Keras:

```python
from keras.wrappers.scikit_learn import KerasClassifier, KerasRegressor
```

You can pass number of epochs as `epochs` parameter during initialization:
```python
KerasClassifier(build_fn=keras_model, epochs=2, batch_size=32, verbose=0)
```

Look at [**full example**](https://github.com/vecxoz/vecstack/blob/master/examples/03_classification_with_proba_detailed_workflow.ipynb) (section *Initialize 1st level models*).
