### ISSUE TITLE
There is some question about transfrom

### ISSUE THREAD

**Issue by zhaobin19941008** [vecxoz/vecstack#24]
When i use Stacking and StackingTransformer for lst layer, there is some difference in specific model OOF which i use AdaBoost, (e.g  (0.9 0.805)  (1.3  1.34)  )so i really don not know  what caused this problem,.

**Comment by zhaobin19941008** [comment]
And there is no difference in other specific model OOF  which i use other methods

**Comment by vecxoz** [comment]
Have you set `random_state` for `AdaBoost`?

Please supply more details and post your code example.
