### ISSUE TITLE
ImportError: cannot import name 'stacking', same issue with StackingTransformer

### ISSUE THREAD

**Issue by uttamdhakal** [vecxoz/vecstack#26]
I can't import Vecstack. I pip3 installed it, uninstalled all the dependencies and installed vecstack again. Still, no luck.

**Comment by vecxoz** [comment]
Please tell me all details:
* command you run to install vecstack and its output
* command you run to start Python interpreter
* command you run to import vecstack 
* info about your system (use the following code):

```python
import sys
import numpy
import scipy
import sklearn

print(sys.platform)
print(sys.version)
print('numpy:', numpy.__version__)
print('scipy:', scipy.__version__)
print('sklearn:', sklearn.__version__)
```

**Comment by uttamdhakal** [comment]
- pip3 install vecstack
- I am using pycharm
- from vecstack import StackingTransformer
- This is my sysinfo: 

- linux
- 3.6.7 (default, Oct 22 2018, 11:32:17) 
- [GCC 8.2.0]
- numpy: 1.16.2
- scipy: 1.2.1
- sklearn: 0.20.3

Thanks

**Comment by vecxoz** [comment]
Thanks! Your system and commands look like OK. I need a bit more info.

1. What is the name of file where you edit code? 
    * The name cannot be `vecstack.py` because it will lead to circular import. 
    * And also import directories must NOT contain any other folders or files with name `vecstack`, e.g. `vecstack.pyc`.

2. Try to do import without PyCharm. Open terminal and start Python interpreter:
`$ python3`
Then try to do import:
`>>> import vecstack`
`>>> print(vecstack.__version__)`
`>>> from vecstack import StackingTransformer`
Post full error traceback.

3. What is the version of PyCharm? What is the type (community)? How PyCharm was installed?

4. Run in terminal the following commands and post their output:
`echo $PATH`
`which python3`
`which pip3`
`python3 --version`
`pip3 --version`

**Comment by uttamdhakal** [comment]
Yes, I have named my file `vecstack.py`. Sorry, that was dumb of me. My bad!

**Comment by vecxoz** [comment]
No problem. I'm glad it was solved.
