### ISSUE TITLE
Metric parameter failing for f1_score metric for multi class classification

### ISSUE THREAD

**Issue by insomniac-klutz** [vecxoz/vecstack#40]
![Screenshot_2020-08-24 Google Colaboratory](https://user-images.githubusercontent.com/42043829/91036502-1644af80-e625-11ea-8629-6ba2806fe591.png)

Recently I faced this issue while using vecstack for a multicalss classification dataset

![Screenshot_2020-08-24 Google Colaboratory1](https://user-images.githubusercontent.com/42043829/91036700-6d4a8480-e625-11ea-9fa6-11c546797c62.png)

It occurs because I am not able to specify that my metric should use attribute avearge='weighted'

I had a look at the source code and I think I can fix this issue.

@vecxoz Can I go ahead and submit a pull request?

**Comment by vecxoz** [comment]
Hi! Thanks for using vecstack.

In order to pass additional arguments to the metric function you can create a wrapper:

```python
def f1_score_wrap(y_true, y_pred):
    return f1_score(y_true, y_pred, average='weighted')
```
