### ISSUE TITLE
Can I use GPU with Vecstack to speed-up the process?

### ISSUE THREAD

**Issue by webzest** [vecxoz/vecstack#42]
Hi, Thank you for your code.  It is GREAT!!!  Is it possible for me to use my GPU to stack / ensemble my models to speed-up the processing and generate the predictions?

**Comment by vecxoz** [comment]
Hi,
Thank you!

You can use GPU. Hardware usage is determined only by the individual models in your stack (e.g. `KerasClassifier`, `XGBClassifier`). Vecstack by itself does not require any additional setup. So first of all you need to setup you models to run on GPU and check if they can do so without vecstack. If yes vecstack will automatically run your models on GPU.
