### ISSUE TITLE
Would it be possible to use Vecstack with a Neural Network?

### ISSUE THREAD

**Issue by webzest** [vecxoz/vecstack#46]
Hi,

I used Vecstack to perform a regression with 12 regressors and get a pretty good prediction, after performing an exhausting tuning of each of the 12 estimators.  However, I reached a point that adding a 13th estimator starts to denigrate the score (might be over fitting at this point).  

I was able to run a kerras neural network on the same data, but it is not performing very well and my predictions are not very accurate.

So, I was wondering, if I could now add a kerras neural network into the mix to see if I can increase the accuracy of the predictions for a Housing Pricing dataset from Kaggle.  If that is possible, how would I go about it?

**Comment by vecxoz** [comment]
Hi,

Of course you can try neural nets in your stack. You just need scikit-learn wrapper: [`KerasRegressor`]( https://www.tensorflow.org/api_docs/python/tf/keras/wrappers/scikit_learn/KerasRegressor). Here is an [example notebook]( https://github.com/vecxoz/vecstack/blob/master/examples/03_classification_with_proba_detailed_workflow.ipynb) for classification. Logic is the same for regression task. You just need to change your net accordingly.

**Comment by webzest** [comment]
Ok...  I am not seeing how to use the NN with my current solution.  for example,  I am currently using this approach, excluding the pipeline section:
https://github.com/vecxoz/vecstack/blob/master/examples/04_sklearn_api_regression_pipeline.ipynb

I was able to configure a NN with this piece of code:
```
from keras import metrics
#create model

def create():
    model_mc = Sequential()

    #add model layers
    model_mc.add(Dense(30, input_dim=X_train.shape[1], activation='relu'))
    model_mc.add(Dense(90, activation='relu'))
    model_mc.add(Dense(120, activation='relu'))
    model_mc.add(Dense(1))

    #compile model using mse as a measure of model performance
    model_mc.compile(optimizer='adam', loss='mean_squared_error', metrics =[metrics.mae]) 

    return model_mc  

model_mc = create().summary()
model_mc = create()
```
How would you proceed to stack the NN with my existing regression model?

**Comment by webzest** [comment]
Hello Vecxoz,

I was able to slow-down and read your response and was able to configure the KerasRegressor() into a stacking() method.  It works with the train_test_split data; however, when I introduce the unknown data, it fails with the following:
`ValueError: Found input variables with inconsistent numbers of samples: [1459, 292]`

In my initial approach, I am using the StackingTransformer() method and it works well because I am able to transform the unknown data and to also create a final_estimator, etc.  

Is it possible for me to use the KerasRegressor() with the StackingTransofrmer()?  I tried it but it is failing.  Here is a short view of how I tried to implement it into the StackingTransformer()

```
...
estimators = [
    ('ExtraTreesRegressor', ExtraTreesRegressor(min_samples_leaf=1, min_samples_split=2, n_estimators=250, n_jobs=-1, random_state=42)),
    ('SVR', SVR(C=2.0, gamma='scale', kernel='poly', degree=3,  shrinking=True, tol=2.0)),
    ('CatBoostRegressor', CatBoostRegressor(iterations=500, learning_rate=0.5, depth=3, l2_leaf_reg=1, border_count=200, random_state=42, silent=True)),
    ('KerasRegressor'), KerasRegressor(build_fn=create(), epochs=2, batch_size=32, verbose=0)
]

# Initialize StackingTransformer
stack = StackingTransformer(estimators, regression=True, n_folds=6, shuffle=True, random_state=42, verbose=0)

# Fit
stack = stack.fit(X_train, Y_train)
```

Please let me know if there is a way for me to use Keras with the StackingTransformer().

**Comment by vecxoz** [comment]
Hi,

Basically everything in your code is correct except the `build_fn` argument. You must pass function itself (i.e. function name without parentheses) not the value returned by the function. Also in general it is recommended to use `tensorflow.keras` instead of `keras`. Here is self-contained example:

```python
from sklearn.datasets import load_boston
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, mean_absolute_error
from sklearn.linear_model import LinearRegression
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.wrappers.scikit_learn import KerasRegressor
from vecstack import StackingTransformer

#------------------------------------------------------------------------------
#------------------------------------------------------------------------------

boston = load_boston()
X, y = boston.data, boston.target
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

#------------------------------------------------------------------------------
#------------------------------------------------------------------------------

def create():
    model = Sequential()
    model.add(Dense(30, input_dim=X_train.shape[1], activation='relu'))
    model.add(Dense(90, activation='relu'))
    model.add(Dense(120, activation='relu'))
    model.add(Dense(1))
    model.compile(optimizer='adam', loss='mean_squared_error', metrics=['mean_absolute_error'])
    return model

#------------------------------------------------------------------------------
#------------------------------------------------------------------------------

estimators = [
        ('lr', LinearRegression(n_jobs=-1)),
        ('keras', KerasRegressor(build_fn=create, epochs=15, batch_size=32, verbose=0)),
]

#------------------------------------------------------------------------------
#------------------------------------------------------------------------------

stack = StackingTransformer(estimators, 
                            regression=True, 
                            variant='A',
                            metric=mean_absolute_error,
                            n_folds=4,
                            shuffle=True, 
                            random_state=0,
                            verbose=2)

stack = stack.fit(X_train, y_train)

S_train = stack.transform(X_train)
S_test = stack.transform(X_test)
```

**Comment by webzest** [comment]
Very nice; good catch!  It is not failing, but (the big but), unfortunately for me, adding keras did not improve my score; it made it worst.  I tried to tune the epochs=10, batch_size=20, but still remained on the high side.  i.e., with my existing 12 estimators, I am at 0.11390, which is not bad, adding keras with those params increased the score to 0.11466.

Would you have any recommendations as to increase the accuracy and reduce the score to at least below 0.10... ?

**Comment by vecxoz** [comment]
This situation is normal. When you build an ensemble you will always see saturation at some point when it becomes hard to find new source of improvement. Some models can’t reach required score level to contribute to ensemble, other ones are highly correlated, some models just don’t mix well with others. And the only recommendation is just experiment. As always you can try some creative feature engineering and some new algorithms.

**Comment by webzest** [comment]
Interesting...  after adding the keras NN model to the list, and adding and extra 200 to the n_estimator, I was able to reduce the error from 0.11397 to 0.11391.  Hahaha  :)  Not much gain.

**Comment by webzest** [comment]
Hello again,

I tried to implement the PolynomialFeatures() to try to improve the socre, but it is failing on the stack.fit method.  Have you have any luck or success with that approach?

```
poly_features = PolynomialFeatures(degree=2)
X_train = poly_features.fit_transform(X_train)

# Initialize StackingTransformer
stack = StackingTransformer(estimators, regression=True, n_folds=6, shuffle=True, random_state=42, verbose=0)
stack = stack.fit(X_train, Y_train)
```

**Comment by vecxoz** [comment]
Hi,

There is not enough information about `stack.fit` fail. I need at least error traceback. But of course `vecstack` should work with `PolynomialFeatures`.

Regarding `PolynomialFeatures` in general and whether this transformation could improve the score I recommend you to ask such questions on Kaggle forum. Thousands of kagglers are solving the same task so I guess you will get a lot of interesting insights there.
